### ISSUE TITLE
Followers and following functionality of social media app.

### ISSUE THREAD

**Issue by YashModi9890** [shreyanshaarvi/no_code_academy#20]
Create a Followers and following functionality like instagram. Where we can show the no. of followers and followings. When click on followers the all list of users will shown with name same with "following".

I tried to do this but only I can achieved is the followers functionality and also not properly.

and I am using the business profile collection to store the user reference list of followers.

**Comment by shreyanshaarvi** [comment]
Will be released soon....

**Comment by YashModi9890** [comment]
Thanks Bro appreciate your work.

**Comment by shreyanshaarvi** [comment]
Issue resolved
