### ISSUE TITLE
Firebase Security Rules

### ISSUE THREAD

**Issue by bhaskar303** [shreyanshaarvi/no_code_academy#6]
Make tutorial on setting up Firebase security rules & adding correct permissions for different data.

**Comment by shreyanshaarvi** [comment]
The request is accepted and will be reviewed soon.

**Comment by shreyanshaarvi** [comment]
The video is created and uploded.
Check it from here :- https://youtu.be/xUAea7sppVw

**Comment by shreyanshaarvi** [comment]
For any other issue create a new one
